### ISSUE TITLE
Missing Images in all Modules

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals.ko-kr#1]
# Module: ALL

Images are missing.  When can we expect these to be added to the repo?

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
All present in https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals.ko-kr/tree/OLPRODLOC/Instructions/Labs/images
